name: nomad
root: ~/src/devOps/nomad/
on_project_first_start: direnv allow

on_project_stop: stop-all-nomad-jobs

pre_window: source .venv/bin/activate

windows:

# sudo ip link add name mylo type dummy && sudo ip address add 172.16.10.65/26 dev mylo
  - con-client: consul-client-start
  - con-client2: sleep 1 && consul-client2-start
  - con-server: sleep 3 && consul-server-start
  - con-esm: sleep 3 && consul-esm-start
#  - config-data: sleep 5 && python cli/load-consul-kv.py

  - nmd: sleep 0 && nomad agent -config cli/configs/nomad-client-server.hcl

#  - res: cd resources/ && sleep 10 && envconsul -log-level="err" -consul-addr=172.16.10.65:8500 -prefix nomad- ../cli/bin/webserver-start
  - monitor: sleep 10 && envconsul -log-level="err" -consul-addr=172.16.10.65:8500 -prefix nomad- python cli/servers/consul-monitor.py

  - jobs: sleep 25 && cli/start-nomad-jobs betika/betradar
#  - jobs: sleep 15 && cli/start-nomad-jobs devOps/g
#  - jobs: sleep 15 && cli/start-nomad-jobs general/postgres
#  - jobs: sleep 15 && cli/start-nomad-jobs general/mysql
#  - jobs: sleep 15 && cli/start-nomad-jobs general/redis
#  - jobs: sleep 15 && cli/start-nomad-jobs general/sonarqube
#  - jobs: sleep 15 && cli/start-nomad-jobs general/sonarqube-custom
#  - jobs: sleep 25 && cli/start-nomad-jobs general/rabbitmq
#  - jobs: sleep 15 && cli/start-nomad-jobs devOps/logs
#  - jobs: sleep 15 && cli/start-nomad-jobs devOps/p

#  - jobs: sleep 15 && cli/start-nomad-jobs spark/spark
#  - jobs: sleep 15 && cli/start-nomad-jobs spark/hadoop
#  - jobs: sleep 15 && cli/start-nomad-jobs bin-repos/npm
#  - jobs: sleep 30 && cli/start-nomad-jobs sb/payments/db
#  - jobs: sleep 30 && cli/start-nomad-jobs devOps/dev

#  - jobs: sleep 15 && cli/start-nomad-jobs sb/sandbox
#  - jobs: sleep 15 && cli/start-nomad-jobs sb/kd
#  - jobs: sleep 15 && cli/start-nomad-jobs sb/sbox
#  - jobs: sleep 15 && cli/start-nomad-jobs poc/php
#  - jobs: sleep 15 && cli/start-nomad-jobs poc/flb
#  - jobs: sleep 15 && cli/start-nomad-jobs poc/fabio-test2
#  - jobs: sleep 15 && cli/start-nomad-jobs devOps/es
#  - jobs: sleep 15 && cli/start-nomad-jobs devOps/l
#  - jobs: sleep 15 && cli/start-nomad-jobs devOps/demo
#  - jobs: sleep 15 && cli/start-nomad-jobs devOps/mss

#  - jobs: sleep 15 && cli/start-nomad-jobs orion/mktplace
#  - jobs: sleep 25 && cli/start-nomad-jobs bin-repos/nexus
#  - hap: sleep 60 && envconsul -log-level="err" -consul-addr=172.16.10.65:8500 -log-level="err" -prefix haproxy-config- haproxy-start

#  - mitmp: sleep 12 && envconsul -log-level="err" -consul-addr=172.16.10.65:8500 -prefix mitmproxy-config- mitmproxy-start
#  - hverf: sleep 12 && envconsul -log-level="err" -consul-addr=172.16.10.65:8500 -prefix hoverfly-config- -prefix mitmproxy-config- hoverfly-start
#  - gor: sleep 12 && envconsul -log-level="err" -consul-addr=172.16.10.65:8500 -prefix gor-config- gor-start
#  - toxp: sleep 12 && envconsul -log-level="err" -consul-addr=172.16.10.65:8500 -prefix toxiproxy-config- toxiproxy-server-start

#  - prom: sleep 12 && envconsul -log-level="err" -consul-addr=172.16.10.65:8500 -prefix prometheus-config- prometheus-start
#  - graf: sleep 12 && envconsul -log-level="err" -consul-addr=172.16.10.65:8500 -prefix grafana-config- grafana-start

#  - cadvisor: sleep 8 && cadvisor

#  - node_ex: sleep 12 && envconsul -log-level="err" -consul-addr=172.16.10.65:8500 -prefix node_exporter-config- node_exporter-start
#  - alertmgr: sleep 12 && envconsul -log-level="err" -consul-addr=172.16.10.65:8500 -prefix alertmanager-config- alertmanager-start
#  - grk_ex: sleep 12 && envconsul -log-level="err" -consul-addr=172.16.10.65:8500 -prefix grok_exporter-config- grok_exporter-start

