
groups:
- name: example
  rules:
    - alert: InstanceDown
      expr: up{instance="host.docker.internal:4000",job="service-node"} == 0
      for: 30s
      labels:
        severity: page
      annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
