#!/usr/bin/env bash

# shellcheck disable=SC2231
for filename in dev/$1/*.nomad-job.template; do
   envconsul -consul-addr=172.17.0.2:8500 -prefix nomad- python cli/run-nomad-job.py "${filename}"
   sleep 5
done

# envconsul -prefix nomad- python cli/run-nomad-job.py dev/gw/files_service.nomad-job.template
# envconsul -prefix nomad- python cli/run-nomad-job.py dev/gw3/krakend_service.nomad-job.template

# envconsul -prefix nomad- python cli/run-nomad-job.py dev/t/service_a_debian.nomad-job.template